plugins:
  - rubocop-rails

inherit_gem:
  rubocop-rails:
    - config/default.yml

AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
    - '**/Gemfile'
    - '**/Capfile'

  Exclude:
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'bin/*'
    - 'config/initializers/*'
    - 'config/environments/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'

  NewCops: enable

  TargetRubyVersion: 3.3 

Rails:
  Enabled: true


Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes